### ISSUE TITLE
attaching usb devices

### ISSUE THREAD

**Issue by NotsOverflow** [tklengyel/xen#1]
hello tklengyel,
not sure if it's an issue but i found nothing on internet.
i get this error wen trying to attache USB device using the configuration file.

```
libxl: error: libxl_dm.c:2339:device_model_spawn_outcome: Domain 11:domain 11 device model: spawn failed (rc=-3)
libxl: error: libxl_create.c:1501:domcreate_devmodel_started: Domain 11:device model did not start: -3
libxl: error: libxl_dm.c:2453:kill_device_model: Device Model already exited

```
all i did is add this to the configuration file:
```
usb = 1
usbdevice="host:148f:3070"
```
and tried to create the domU.

I posted it here since I use this xen and the drakvuf tutorial.
btw thanks for the tool, it's really usefull :)

**Comment by tklengyel** [comment]
Please post xen related issues to the appropriate mailinglist at https://lists.xenproject.org/mailman/listinfo/xen-users
