### ISSUE TITLE
vga_console_info undeclared in boot-efi.h

### ISSUE THREAD

**Issue by d34d10cc** [tklengyel/xen#2]
There is an error caused by [this line](https://github.com/tklengyel/xen/blob/fbdaa641e3e76861c72b95ef59fbf257f7ef2f2e/xen/arch/x86/efi/efi-boot.h#L328).
```
efi-boot.h:328:32: error: ‘vga_console_info’ undeclared (first use in this function); did you mean ‘xen_vga_console_info’?
     xenmbi->vga_console_info = vga_console_info;
```
This occurs another few times in the file as well. I couldn't figure out what's wrong. The other global variables in the same block of code are supplied by a header (I'm assuming indirectly included), and this one is supposed to be supplied by `vga.h`, but I can't see a reason it's not.

**Comment by tklengyel** [comment]
I've seen that error before but it is the result of an unclean build. Make sure you have a fresh checkout (or run `git clean -xdf` + remove any firmware/qemu repositories that get cloned during xen tools build). It builds fine afterwards.

**Comment by tklengyel** [comment]
Never mind, I see it now too. This is actually related to a new Spectre mitigation Xen added, disabling CONFIG_PV_SHIM in tools/firmware/Makefile makes it go away.

**Comment by tklengyel** [comment]
I've pushed an update to the submodule in the `xen-uefi` folder that fixes it.
